---
engines:
  golint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - golang
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.go"
exclude_paths:
    - "*/Godeps/"
